version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    image: mongo
    restart: always
    ports:
      - "27107:27017"
    volumes:
      - mongo_data:/data/db

  catalog-api:
    container_name: catalog.api
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: D:\Microservices\aspnetMicroservice\src\Services\Catalog\Catalog.API\Dockerfile
    ports:
      - "8000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:MongoConnectionString=mongodb://catalogdb:27017"
    depends_on:
      - catalogdb
volumes:
  mongo_data: