version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    image: mongo
    restart: always
    ports:
      - "27107:27017"
    volumes:
      - mongo_data:/data/db

  redisdb:
    container_name: redisdb
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  catalog-api:
    container_name: catalog.api
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: D:\Microservices\aspnetMicroservice\src\Services\Catalog\Catalog.API\Dockerfile
    ports:
      - "8000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:MongoConnectionString=mongodb://catalogdb:27017"
    depends_on:
      - catalogdb

  basket-api:
    container_name: basket.api
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: D:\Microservices\aspnetMicroservice\src\Services\Basket.API\Dockerfile
    ports:
      -  "8081:81"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=redisdb:6379"
    depends_on:
      - redisdb
      
volumes:
  mongo_data:
  redis_data: